name:                knapsack-elvm
version:             0.1.0.0
github:              "nwtgck/knapsack-elvm-haskell"
license:             BSD3
author:              "Ryo Ota"
maintainer:          "nwtgck@gmail.com"
copyright:           "2018 Ryo Ota"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nwtgck/knapsack-elvm-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
 source-dirs: src
 dependencies:
 - mtl
 - array
 - transformers
 - exceptions

executables:
  knapsack-elvm-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knapsack-elvm

tests:
  knapsack-elvm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
#    - knapsack-elvm
